[package]
name = "hypervisor"
version = "0.1.0"
edition = "2024"

[dependencies]
spin = "0.10.0"

allocator.workspace = true
fdt.workspace = true
string_utils.workspace = true
arch = { version = "0.1.0", path = "../arch" }
mmio_core = { version = "0.1.0", path = "../support/mmio_core" }
virtio = { version = "0.1.0", path = "../support/devices/virtio" }
block = { version = "0.1.0", path = "../support/devices/block" }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
allocate_pages = { version = "0.1.0", path = "../support/allocate_pages" }
fat32 = { version = "0.1.0", path = "../support/fat32" }
virtio_core = { version = "0.1.0", path = "../support/virtio_core" }
log = { version = "0.4.29", features = ["max_level_trace"] }
shmem = { version = "0.1.0", path = "../support/shmem" }

[features]
nested_support = []
nested_acceleration = ["nested_support"]
