[workspace]
default-members = ["hypervisor"]
members = [
  "hypervisor", "l1_hypervisor", "support/architecture", "support/string_utils",
]

[workspace.dependencies]
# support crates
allocator = { path = "support/allocator" }
fdt = { path = "support/fdt" }
string_utils = { path = "support/string_utils" }
