[workspace]
resolver = "3"
default-members = ["hypervisor"]
members = [
  "hypervisor",
  "l1_hypervisor",
  "arch",
  "support/allocator",
  "support/fdt",
  "support/string_utils",
  "support/mmio_core",
  "xtask", "support/devices/virtio", "support/devices/block", 
]

[workspace.dependencies]
# support crates
arch = { path = "arch" }
allocator = { path = "support/allocator" }
fdt = { path = "support/fdt" }
string_utils = { path = "support/string_utils" }
