[workspace]
resolver = "3"
default-members = ["hypervisor"]
members = [
  "hypervisor",
  "l1_hypervisor",
  "arch",
  "support/allocator",
  "support/fdt",
  "support/string_utils",
  "xtask", "device/virtio", "device/serial/ns16550", "support/mmio",
]

[workspace.dependencies]
# support crates
arch = { path = "arch" }
allocator = { path = "support/allocator" }
fdt = { path = "support/fdt" }
string_utils = { path = "support/string_utils" }
